FORMAT: 1A

# Survaider
Survaider REST API documentation for survey and responses endpoints.

# My Message [/message]
OK, `My Message` probably isn't the best name for our resource but it will do for now. Note the URI `/message` is enclosed in square brackets.

## Retrieve a Message [GET]
Now this is informative! No extra explanation needed here. This action clearly retrieves the message.

+ Response 200 (text/plain)

        Hello World!

## Update a Message [PUT]
`Update a message` - nice and simple naming is the best way to go.

+ Request (text/plain)

        All your base are belong to us.

+ Response 204