FORMAT: 1A

# Survaider
Survaider REST API documentation for survey and responses endpoints.

# Surveys [/api/survey]
Authentication is required to access this endpoint.

## Retrieve List of Surveys [GET]
Returns all the Surveys created by the user.

+ Response 200 (application/json)

        {
            "data": [
                {
                    "id": "r88Wnmz8NJOm2q61ZM4",
                    "name": "Demo 1",
                    "uri": "/survey/s:r88Wnmz8NJOm2q61ZM4/simple",
                    "uri_edit": "/survey/s:r88Wnmz8NJOm2q61ZM4/edit"
                },
                {
                    "id": "OLL8rLJvgzlQ38oMwdo",
                    "name": "Demo 2",
                    "uri": "/survey/s:OLL8rLJvgzlQ38oMwdo/simple",
                    "uri_edit": "/survey/s:OLL8rLJvgzlQ38oMwdo/edit"
                },
                {
                    "id": "YzzA2vJ5XA4X49Qpj4M",
                    "name": "Demo 3",
                    "uri": "/survey/s:YzzA2vJ5XA4X49Qpj4M/simple",
                    "uri_edit": "/survey/s:YzzA2vJ5XA4X49Qpj4M/edit"
                },
            ],
            "owner": "5621fdd6da1dd241bfc4db3c",
            "survey_count": 3
        }

+ Response 400 (application/json)

        {
            "error": true,
            "message": "Authentication Required"
        }

## Create a new Survaider [POST]
Creates a new Survaider. Authentication Required.

+ Request (application/json)

        {
            "s_name": "Demo Survey Name",
            "s_desc": "Demo Survey Description"
        }

+ Response 200

        {
            id: "8NNaDvdGm3J1qwzDLbd"
            uri: "/survey/s:8NNaDvdGm3J1qwzDLbd"
            uri_edit: "/survey/s:8NNaDvdGm3J1qwzDLbd/edit"
        }

+ Response 400 (application/json)

        {
            "error": true,
            "message": "Authentication Required"
        }

# Survey [/api/survey/{survey_id}]
Authentication is general

