mouseX = 0
mouseY = 0
windowHalfX = window.innerWidth / 2
windowHalfY = window.innerHeight / 2
SEPARATION = 200
AMOUNTX = 10
AMOUNTY = 10
camera = undefined
scene = undefined
renderer = undefined

init = ->
  container = undefined
  separation = 100
  amountX = 50
  amountY = 50
  particles = undefined
  particle = undefined
  camera = new THREE.PerspectiveCamera 75, window.innerWidth / window.innerHeight, 1, 10000
  camera.position.z = 100
  scene = new THREE.Scene
  renderer = new THREE.WebGLRenderer alpha: true
  renderer.setSize window.innerWidth, window.innerHeight
  document.getElementById('bg').appendChild renderer.domElement
  # particles
  PI2 = Math.PI * 2
  geometry = new THREE.Geometry
  i = 0
  while i < 100
    material = new THREE.SpriteMaterial
      color: do ->
        a = Math.ceil(Math.random() * 10)
        switch a
          when 0
            return 0x99b433
          when 1
            return 0x00a300
          when 2
            return 0x1e7145
          when 3
            return 0x9f00a7
          when 4
            return 0x7e3878
          when 5
            return 0x603cba
          when 6
            return 0x00aba9
          when 7
            return 0xeff4ff
          when 8
            return 0xb91d47
          when 9
            return 0xe3a21a
          else
            return 0x00aba9
        return
      opacity: 0.8
      program: (context) ->
        context.beginPath()
        context.arc 0, 0, 0.5, 0, PI2, true
        context.fill()
        return

    particle = new THREE.Sprite material
    particle.position.x = Math.random() * 2 - 1
    particle.position.y = Math.random() * 2 - 1
    particle.position.z = Math.random() * 2 - 1
    particle.position.normalize()
    particle.position.multiplyScalar Math.random() * 10 + 800
    particle.scale.x = particle.scale.y = 10
    scene.add particle
    console.log i
    geometry.vertices.push particle.position
    i++

  line = new (THREE.Line)(geometry, new (THREE.LineBasicMaterial)(
    color: 0x444444
    opacity: 0.4))
  scene.add line
  document.addEventListener 'mousemove', onDocumentMouseMove, false
  window.addEventListener 'resize', onWindowResize, false
  return

onWindowResize = ->
  windowHalfX = window.innerWidth / 2
  windowHalfY = window.innerHeight / 2
  camera.aspect = window.innerWidth / window.innerHeight
  camera.updateProjectionMatrix()
  renderer.setSize window.innerWidth, window.innerHeight
  return

#

onDocumentMouseMove = (event) ->
  mouseX = event.clientX - windowHalfX
  mouseY = event.clientY - windowHalfY
  return


animate = ->
  requestAnimationFrame animate
  render()
  return

render = ->
  camera.position.x += (mouseX - (camera.position.x)) * .05
  camera.position.y += (-mouseY + 200 - (camera.position.y)) * .05
  camera.lookAt scene.position
  renderer.render scene, camera
  return

init()
animate()

# ---
# generated by js2coffee 2.1.0
